# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/hikaritsai/JS_Inflator/libs/r8brain-free-src/CMakeLists.txt))

/Users/hikaritsai/JS_Inflator/build-aax-sdk/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/bin/cmake -S/Users/hikaritsai/JS_Inflator -B/Users/hikaritsai/JS_Inflator/build-aax-sdk
